### ISSUE TITLE
Train with pre_extracted = False

### ISSUE THREAD

**Issue by rvermeire** [marco-rudolph/cs-flow#1]
When I run main.py with pre_extracted = False the follwoing assertion fails on line 522 of freia_funcs.py

```
assert len(input_vars) == 1, (f"Got single input tensor for "
AssertionError: Got single input tensor for forward pass, but expected list of 3.
```

**Comment by scuShaker** [comment]
> When I run main.py with pre_extracted = False the follwoing assertion fails on line 522 of freia_funcs.py
> 
> ```
> assert len(input_vars) == 1, (f"Got single input tensor for "
> AssertionError: Got single input tensor for forward pass, but expected list of 3.
> ```

I got the problem too , have you solved it?

**Comment by marco-rudolph** [comment]
As mentioned in the Readme, features can be extracted by executing _extract_features.py_. This is recommended to speed up training.
The latest commit supports training with pre_extracted=False.

**Comment by rvermeire** [comment]
Hi Marco, thanks for the quick fix! I think evaluate.py has the same issue and that was the main reason I reported it. If I understand correctly every unseen image in training has to have its features extracted during inference/evaluation. For use in industrial manufacturing this would be done in memory I guess?

**Comment by marco-rudolph** [comment]
You are right, I just modified _evaluate.py_ as well. 

> If I understand correctly every unseen image in training has to have its features extracted during inference/evaluation. For use in industrial manufacturing this would be done in memory I guess?

This is correct.
