### ISSUE TITLE
Possible mistake in the likelihood_grouped calculation

### ISSUE THREAD

**Issue by ira7bar** [marco-rudolph/cs-flow#10]
In [line 177 of evaluate.py](https://github.com/marco-rudolph/cs-flow/blob/main/evaluate.py#L177), the mean is calculated and then divided by the number of channels.
Before the division the values are similar to the anomaly score (nll_score) and make sense. 
Perhaps the division is not needed as the mean operation already includes division by the number of channels?

This does not affect the visualization, as the heatmap is normalized anyway by the plotting function, but maybe good to fix it for other purposes and for correctness.

**Comment by marco-rudolph** [comment]
Thank you. It is fixed with the latest commit.
