### ISSUE TITLE
Can a single cs-NF detect defects of objects of multiple categories?

### ISSUE THREAD

**Issue by IzouGend** [marco-rudolph/cs-flow#11]
Thanks for excellent work and code! I notice every category needs a cs-NF in released code. Here I have a question:
Can a single cs-NF detect defects of objects of multiple categories?

**Comment by marco-rudolph** [comment]
Yes it works, but the performance is slightly lower as for the individual classes. In the case of MVTec, the detection AUROC dropped by 0.5% on average.

**Comment by IzouGend** [comment]
Thank you the explanation！
