### ISSUE TITLE
Test the good image

### ISSUE THREAD

**Issue by gaowq2017** [marco-rudolph/cs-flow#12]
Hi, 
Thank you for sharing the code, i want test the good image by note line 110-111 in evaluate.py
![image](https://user-images.githubusercontent.com/29697367/157405130-c3247009-f71d-43fa-a525-86838c1bbdd2.png)
or any ideas? Thank you

**Comment by marco-rudolph** [comment]
Hi,

have you tried to just delete the lines 110-111?
A problem here is that the visualized map is normalized such that small scores could be highlighted if the highest score within a map is quite low. In this case, you have to find and set the same vmin and vmax value in plt.imshow for all images which would make them comparable.
see vmin and vmax: https://matplotlib.org/3.5.1/api/_as_gen/matplotlib.pyplot.imshow.html

Hope that helps
Marco
