### ISSUE TITLE
 The size of tensor a (15) must match the size of tensor b (14) at non-singleton dimension 3

### ISSUE THREAD

**Issue by DeepSpace98** [marco-rudolph/cs-flow#14]
I use my dateset to run main.py, my image's size is (640,480),I only change img_size,but it don't work.what should I do?

**Comment by marco-rudolph** [comment]
Image width/height should be a multiple of 128. Sorry I did not specify this, I will do it in the next commit.

**Comment by DeepSpace98** [comment]
> Image width/height should be a multiple of 128. Sorry I did not specify this, I will do it in the next commit.

Must be 128?Then what should I do to make my picture can be trained?

**Comment by marco-rudolph** [comment]
Not 128, a multiple of 128. So you could set the image size for example to (512, 384) or (768, 512). Images will be resized automatically according to the given values.

**Comment by DeepSpace98** [comment]
> Not 128, a multiple of 128. So you could set the image size for example to (512, 384) or (768, 512). Images will be resized automatically according to the given values.

Thank you for your reply, I still have a problem.If I want to use the trained model to predict a image not eval, what should I do,I didn't see some parties related to prediction in the file.

**Comment by marco-rudolph** [comment]
I don't get the question. What do you want to do?
For user-specific evaluations and outputs, please write your own code.

**Comment by DeepSpace98** [comment]
> I don't get the question. What do you want to do? For user-specific evaluations and outputs, please write your own code.

I want to try change the  efficientnet-b5 to b4, when I run extract_features.py, https://github.com/marco-rudolph/cs-flow/blob/04bbc62153d331daa447fdc2957a9efd585093a3/extract_features.py#L26
has error "zero-dimensional arrays cannot be concatennated";
from b5 to b4, Is it enough to change extractor and n_feat? If no,can you teach me how to change to use other efficientnet ?

**Comment by marco-rudolph** [comment]
You have to change the chosen layer index (named "use_layer") here to a value less equal 31:
https://github.com/marco-rudolph/cs-flow/blob/04bbc62153d331daa447fdc2957a9efd585093a3/model.py#L47
Since the maximum index of b4 is 31, the function returns None.
