### ISSUE TITLE
Why is the anomaly score z^2?

### ISSUE THREAD

**Issue by BenediktAlkin** [marco-rudolph/cs-flow#18]
Hi!

I've been playing around with DifferNet and CS-Flow and am wondering why the [anomaly score](https://github.com/marco-rudolph/cs-flow/blob/ac78bd192c80866ab8db2b8b483650881e6ea44c/train.py#L80) is set equal to z^2. 

z^2 is basically the likelihood that z comes from a standard normal distribution, but the model is anyway trained with the likelihood of the input sample on the data distribution. Shouldn't the data likelihood (as calculated [here](https://github.com/marco-rudolph/cs-flow/blob/ac78bd192c80866ab8db2b8b483650881e6ea44c/utils.py#L26)) be a better anomaly score since we don't necessarily care about how well the transformed input sample is of a normal distribution, but how likely it is that an input sample is of the real data distribution?

I tried using the data likelihood as anomaly score and while it didn't really change the results for MVTec, it greatly improved (by up to 0.1 AUC) the performance on another dataset.

**Comment by marco-rudolph** [comment]
In fact, it would theoretically make sense to include the Jacobian. However, in our experiments, this has been found to degrade performance in some cases. Apparently, however, there are also cases where it is helpful to use it.

**Comment by BenediktAlkin** [comment]
I see, thanks for your quick response!
