### ISSUE TITLE
n_scales parameter

### ISSUE THREAD

**Issue by CharlesAntoineParent** [marco-rudolph/cs-flow#19]
Hello ! I was wondering why there was an option to configure the number of scale produce by the feature extractor if nf blocks are always supposed to get 3 scales ?
Thank you

**Comment by marco-rudolph** [comment]
Hi,
unfortunately, there is currently no option to configure the number of scales. n_scales is used for many parts of the code for readability, but not for the NF architecture itself.

Best regards,
Marco Rudolph

**Comment by CharlesAntoineParent** [comment]
Thank you for the quick answers. I was wondering if you tried getting multi scale representation by using a backbone that produces different scales only with one propagation (like Darknet + Path aggregation network in yolo) instead of getting representation by doing multiple propagation in the backbone ?

**Comment by marco-rudolph** [comment]
I tried this, but got a slightly worse performance for MVTec. It might be beneficial for other datasets.
