### ISSUE TITLE
AssertionError: Got single input tensor for forward pass, but expected list of 3

### ISSUE THREAD

**Issue by xfby2016** [marco-rudolph/cs-flow#2]
Hi，when I set pre_extracted = False, It report the following errors :
assert len(input_vars) == 1, f"Got single input tensor for " AssertionError: Got single input tensor for forward pass, but expected list of 3
Any advice?

**Comment by guyiyifeurach** [comment]
How you solved your problem? I met the same problem. Thank you! @xfby2016

**Comment by xfby2016** [comment]
> How you solved your problem? I met the same problem. Thank you! @xfby2016

yes,marco-rudolph has solved the problem in the latest code

**Comment by guyiyifeurach** [comment]
I pull, and this question solve, but when pre_extracted = True,I still meet data/features/dumplings/dumplings_scale_0_train.npy can't find.

**Comment by xfby2016** [comment]
extract_features.py should be  execution before training.
