### ISSUE TITLE
The Details of Magnetic-Tile-Defect Dataset

### ISSUE THREAD

**Issue by dragonlee258079** [marco-rudolph/cs-flow#24]
Dear authors,
     Can you provide the magnetic-tile-defect dataset with detailed training and testing image splitting? 
     Thank you very much.

**Comment by marco-rudolph** [comment]
Hello,
the filenames of the training images are given here:
https://github.com/marco-rudolph/differnet/blob/master/mtd_train_filenames.txt
Best,
Marco
