### ISSUE TITLE
Missing gamma parameter

### ISSUE THREAD

**Issue by ashwinvaidya17** [marco-rudolph/cs-flow#25]
Hi, maybe I missed it but I am unclear about this line https://github.com/marco-rudolph/cs-flow/blob/5f603047a363dca4e98cf7880db33cda68f4c70a/freia_funcs.py#L201

The paper (equation 3) mentions $\gamma_1$ and $\gamma_2$ learnable parameters in each block. It seems to be missing from this part of the code. Am I looking at the right place?

**Comment by marco-rudolph** [comment]
Hi,
this is the right place: https://github.com/marco-rudolph/cs-flow/blob/5f603047a363dca4e98cf7880db33cda68f4c70a/freia_funcs.py#L106
Best,
Marco

**Comment by ashwinvaidya17** [comment]
Thanks 😃
