### ISSUE TITLE
Is it possible to replace the EfficentNet feature extracrtor by a Mobilnet_v3 model? If yes, what changes should I make?

### ISSUE THREAD

**Issue by Tekno-H** [marco-rudolph/cs-flow#26]
Hello Marco,
Great work you have done here.
I am looking forward to use the cs-flow model on an edge device (jetson). However, the EfficientNet backbone is very computationally expensive, will it be difficult to replace it with a lighter feature extractor like the MobileNet_v3 ?
What changes should be made?
Thanks in advance.

**Comment by marco-rudolph** [comment]
Hey,
thanks!
It is indeed.
1) You have to replace the feature extractor in model.py (https://pytorch.org/vision/main/models/mobilenetv3.html). Depending on which intermediate layer you aim, check the forward function of it and replace the old one.
2) change "n_feat" in config.py (depending on how many features your interm. layer provides)
3) change "map_len" in config.py (depending on your width/height of your new output layer)

Further possibilities to speed up your computation:
- reduce "fc_internal" in config.py
- use only one scale
- reduce image resolution

Best,
Marco

**Comment by Tekno-H** [comment]
Thanks for the quick reply.
I will soon try your propositions and get back to you.

**Comment by Tekno-H** [comment]
Greetings Marco,
I was trying to implement what you proposed, but I faced some issues in the first step.
After I replaced the feature extractor by Mobilenetv3 :
self.feature_extractor = mobilenet_v3_large( weights=MobileNet_V3_Large_Weights, progress=True )
I couldn't figure out what changes should be made in the "eff_ext" and forward method.
I am sorry if I am asking too much, but could you guide me through the changes that should be made ?
Anything helps.

Additionally, I aim to export this model to ONNX after I finish training, have you experimented with that ?

Thanks anyhow :)

**Comment by marco-rudolph** [comment]
You have to take a look in the original pytorch implementation [here](https://pytorch.org/vision/main/_modules/torchvision/models/mobilenetv3.html#mobilenet_v3_large). For example, you can get the features from the last layer before the classification head by replacing "eff_ext" with
`features = self.feature_extractor.features(x)`
To get outputs from other intermediate layers (inside the sequential "features"-model), look [here](https://discuss.pytorch.org/t/how-to-get-a-intermediate-value-from-nn-sequential/19111).

I'm afraid I have no experience with ONNX.

Best,
Marco

**Comment by Tekno-H** [comment]
Thank you very much !
I will try them.

Yesterday,I trained the model using the EfficentNet feature extractor, reaching high AUROC=0.9456.
However it gave poor results.
The produced anomaly maps did not really highlight the correct anomaly regions when I ran evaluate.py.
The only changes I made was decreasing the image size to **(128,128)** (the images in the dataset are of this approximate size) and setting fc_internal to **512**.
I have tried the same dataset with other AD models and they gave much better results.

What do you think may be the problem?

**Comment by marco-rudolph** [comment]
95% AUROC seems quite solid. You may change the x-limit from the histogram above to get a better view of it.
Changing the resolution to 128x128 just makes the localization super coarse, resulting in a 4x4 pixel output. You could either use the features from a previous layer or increase the resolution (even if it was originally smaller) to have a more detailed localization.
