### ISSUE TITLE
Train loss might become negative during training, what does this situation mean?

### ISSUE THREAD

**Issue by WenPX** [marco-rudolph/cs-flow#28]
When I train this model in MVTec-AD datasets, I found that the train loss might becomg negative. What does it mean?

**Comment by marco-rudolph** [comment]
This is normal. As the loss is the negative log likelihood, it can be negative.

**Comment by WenPX** [comment]
Thanks for your reply. That would be very helpful.




WPX.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "marco-rudolph/cs-flow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [marco-rudolph/cs-flow] Train loss might become negative during training, what does this situation mean? (Issue #28)





 
This is normal. As the loss is the negative log likelihood, it can be negative.
