### ISSUE TITLE
Why do you apply data augmentation is that way?

### ISSUE THREAD

**Issue by mjack3** [marco-rudolph/cs-flow#29]
Hello Marco.

The way you apply data augmentation in your previous "DifferNet" catches my attention. Why do you not randomly apply data augmentation? Is it related to enabling the encoder to extract features from the images beforehand? Or do I need to include something more important to my suppositions?

Thanks

**Comment by marco-rudolph** [comment]
Hello,

the data augmentation in DifferNet is mainly to ensure robustness. As the feature extractor is not scale invariant and features are heavily compressed (by average pooling), this boosts the performance heavily (see ablation in paper).

Best,
Marco
