### ISSUE TITLE
About the detection time 

### ISSUE THREAD

**Issue by xfby2016** [marco-rudolph/cs-flow#3]
Hi,when I set pre_extracted = False, running evaluate.py, the calculation time for each image was approximately 0.4 seconds(use cuda),Is there any way to improve the performance? thanks !

**Comment by marco-rudolph** [comment]
Hi,

as long as feature extraction is the bottleneck here with EfficientNet as the feature extractor, you could change the feature extractor (e. g. to AlexNet), select an earlier layer or reduce image size.

Best regards
Marco Rudolph
