### ISSUE TITLE
Size of tensor a must match size of tensor b at non-singleton dimension 3

### ISSUE THREAD

**Issue by MiriamHu** [marco-rudolph/cs-flow#4]
While running `main.py` with my own dataset, I ran into the following: 
 
```
 File "freia_funcs.py", line 101, in forward
    out0 = out0 + y1_up
RuntimeError: The size of tensor a (32) must match the size of tensor b (24) at non-singleton dimension 3
```

**Comment by marco-rudolph** [comment]
I guess you changed some hyperparameter compared to the original code? If so, please report me to adapt the code for this variation. I guess you have to adjust the map_size parameter in _config.py_.

**Comment by MiriamHu** [comment]
Thank you for your suggestion, but the `map_size` parameter is computed based on both the width and height of the input, so not sure what to change there. 
I have only gotten it to run by reshaping the images to be square. I have looked a little bit into where there could be assumptions about square image shapes in your code, but haven't completely zeroed in on it yet unfortunately.

**Comment by marco-rudolph** [comment]
Sorry for the late response, I was on vacation.
I fixed the bug with the latest commit.
