### ISSUE TITLE
Cannot reimplement performance on paper

### ISSUE THREAD

**Issue by DonaldRR** [marco-rudolph/cs-flow#6]
Hey,

I have tried the default config to train MVTec_AD's Cable class, but couldn't reach the performance referred in the paper. 
Is it necessary to fine tune the config for each in order to reimplement the performance?

**Comment by marco-rudolph** [comment]
Sorry for the late response, I was on vacation.
I just found a little error in the configuration (kernel size), with the latest commit the paper-given performance should be obtained.
> Is it necessary to fine tune the config for each in order to reimplement the performance?

No, the paper-given hyperparameters were used for all classes.
